{% set name = "napari-cursor-tracker" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-cursor-tracker-{{ version }}.tar.gz
  sha256: ddf189aef636fb2308d6d617872607d1c8a241abe3a4ebac6506eaa5a7e571cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm
    - wheel
  run:
    - magicgui
    - napari
    - numpy
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - napari_cursor_tracker
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-cursor-tracker
  summary: Plugin for easy manual annotation/tracking of 3D or 2D + t dataset by following the cursor.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/faymanns/napari-cursor-tracker

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
